version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-ai-moderator
    restart: unless-stopped
    ports:
      - "${DASHBOARD_PORT:-3000}:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: discord-ai-moderator-db
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: